# Generated by Django 3.2.9 on 2021-12-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
    ]
